# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-gb
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#fr:
#  locale: fr-fr
#  contentDir: content/fr
#  title: French website title...
#  params:
#    description: Site description in French...
#  menu:
#    main:
#      - name: Accueil
#        url: /
#        weight: 10
