# Navigation Links
#   To link to a section of the homepage, use a hash `#` followed by the `id` of
#   the corresponding block in `content/_index.md`.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Projects
    url: /projects
    weight: 20
  - name: Publications
    url: /publications/
    weight: 30
  # - name: Public speaking
  #   url: /events/
  #   weight: 40
  - name: Contact
    url: /contact/
    weight: 50
  # Link to a PDF of the CV, stored in `static/uploads/`.
  - name: CV
    url: /uploads/cv.pdf
    weight: 60
